### ISSUE TITLE
Site header missing on Android

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#148]
Logged into crowdmap.com on my nexus. it automatically redirects to crowdmap.com/posts.

I can't "create a post"> If i try to go back to only crowdmap.com, it redirects me back to the latest post page. 
![crowdmap mobile android](https://f.cloud.github.com/assets/1216707/467454/8b9c940c-b679-11e2-81e2-c421903a2244.png)

**Comment by evansims** [comment]
Heya;

Redirecting to /posts is OK, that's normal. We're doing that just to avoid caching conflicts when switching between Classic and New. /posts is essentially your homepage for now.
1. Which version of Android are ya on?
2. Is the site header visible to you?
3. If so, what happens when you hit the "+" create post icon? Any errors, or just redirecting to /posts?
4. Can you try heading to /create and see if it works from there?

**Comment by heatherleson** [comment]
1. version - google nexus 4.2.1
2. / 3.  the site header to add a post or map is not visible thus, cannot create a post
3. I can get to /create

**Comment by evansims** [comment]
Thanks — will check into this

**Comment by heatherleson** [comment]
I think that there should be a +create Post icon on the post home page. 

User view - see posts, add posts, see spot run

**Comment by evansims** [comment]
There is one, but the header isn't showing up so you can't see it. :)

**Comment by evansims** [comment]
Header now rendering properly in non-Chrome versions of Webkit on Android.
