### ISSUE TITLE
Upload Image Sizes

### ISSUE THREAD

**Issue by dkobia** [ushahidi/crowdmap-issues#179]
This refs #176. I uploaded this beauty - https://b25c7ada827abcbc0630-5454a9e6f7100566866dd221e5013c79.ssl.cf2.rackcdn.com/5196449c291422.10143506_o.jpg and I think its being rendered to the browser in all its 3.6 MB glory. Maybe have images max out at a specific size?

**Comment by brianherbert** [comment]
I want whatever that food truck produces.

We do resize images into three different sizes, which _should_ display depending on your connection speed. It looks like you're downloading the original file, which isn't right. We should only be displaying the large size (with an _l at the end of the filename instead of _o).

So, you should be seeing https://b25c7ada827abcbc0630-5454a9e6f7100566866dd221e5013c79.ssl.cf2.rackcdn.com/5196449c291422.10143506_l.jpg which is only 384kb.

We'll look into that.

**Comment by evansims** [comment]
Sorry, I didn't see this issue until just now. I don't appear to be getting all my GitHub notifications. Hmph.

Anyway, I just finished implementing [our new image handling library](https://github.com/evansims/uximage). I didn't check if I could reproduce this before, but if it was happening, it definitely won't with this new setup. :)
