### ISSUE TITLE
Add image on iOS doesn't work

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#187]
Trying to add a photo when creating a new post on iOS. Nothing happens when pressed.

**Comment by evansims** [comment]
Doesn't appear the URL parser works on mobile anymore either. Will investigate further.

**Comment by evansims** [comment]
This is resolved. Fix is on staging and will be pushed to production along with other bugfixes this evening.

FYI the issue was that the create post path detection in modal-transitions was changed from /create to /create/post but the mobile header links didn't get updated to match the new path. Thus, crowdmap.post wasn't getting loaded in.
