### ISSUE TITLE
Add maps while creating a post

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#202]
Created post - https://crowdmap.com/post/1395/. When I added the post to maps, there was no ability to create a new map, and then add it. 

It would be helpful to be able to:
Create a post
Within this process, add or create a map
Save. 

This way there are more maps and posts.

**Comment by brianherbert** [comment]
I'm a little hesitant to allow this since the map creation process is a multi-step one, which takes you directly into map settings after creation. My hope is that we have lots of maps but hopefully not lots of empty or single post maps.

Running a map comes with a (low) level of responsibility to moderate, approve posts, and I think if people are making maps without giving it a second thought, it might lead to too many irrelevant or poorly moderated maps.

**Comment by heatherleson** [comment]
ok. closing then
