### ISSUE TITLE
Image Orientation is insane

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#208]
Most images are not being saved right-side up. @evansims, is this something I can look at or are you still investigating? These should be the orientation flags: http://sylvana.net/jpegcrop/exif_orientation.html

Pinging @heatherleson @aoduor @julianar

**Comment by evansims** [comment]
Haha, yeah, I've got this bug in my sights. We're using the flags outlined [here](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/) presently, but I'll compare our current settings with those in your article. What's weird is every test image I throw at our current setup orients the photos properly based on the spec. I've requested Erik and Angela to send me original copies of their images so I can analyze the EXIF metadata and figure out what's up.

**Comment by evansims** [comment]
Well that was a super herp derp on my part. The problem was back in commit [#8f4f78db16](https://github.com/ushahidi/Crowdmap-New/commit/8f4f78db167a9b14ed6a54a894a984cd31de34b9), I forgot to remove the rotation flag from all the steps - it should only have been applied to our 'original'. So it was rotating the smaller versions of the images one time too many. Fixed now!

**Comment by julianar** [comment]
Thank you Evan!
Juliana Rotich
Support our Kickstarter for the BRCK
http://www.kickstarter.com/projects/1776324009/brck-your-backup-generator-for-the-internet

**Comment by aoduor** [comment]
Edited my post and it worked fine. Thank you @evansims and @brianherbert!
