### ISSUE TITLE
Email notifications for new comments not working

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#214]
I haven't received email for the comments on https://crowdmap.com/post/1549/

**Comment by brianherbert** [comment]
@evansims I posted a comment to one of your posts. You didn't happen to get an email for it, did you?

**Comment by evansims** [comment]
Hmmmm nope, no email. Shoot. I wonder when that broke.

**Comment by brianherbert** [comment]
It's getting to the point that we write to the new email log which is right before the actual transmission to sendgrid.

**Comment by evansims** [comment]
So the problem is we're over our monthly allowance over at Send Grid, so they're not delivering our emails anymore. We have no payment information on file so they aren't billing us for overages, they've just stopped sending mail. Our allowance resets on Saturday.

I'm not sure if this is the first time we've hit this wall before or not, there doesn't appear to be a history to look that up. However, given the more verbose nature of New Crowdmap, we need to get payment info on file to handle these instances. Overages are $0.001 per email.

cc @dkobia

**Comment by brianherbert** [comment]
We'll get that taken care of ASAP. The new Crowdmap is definitely more verbose than before.

**Comment by evansims** [comment]
David got us upgraded and I'm noticing emails starting to trickle in. Might take a bit before we catch up, but we should be good on this now.

**Comment by brianherbert** [comment]
Does this send mails retroactively?

**Comment by evansims** [comment]
I think so. I got a handful of emails from the last few days dumped at once.
