### ISSUE TITLE
The ?embed param needs to be persistent when clicking around inside an iframe embed

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#218]
If you add a post or a map as an embed and you click an internal link, the ?embed flag is lost and the Crowdmap header comes back. We need to find a way to keep that persistent.

We may need to have a helper for links that will always keep that persistent. I would use sessions but there's a chance the user is browsing the site and viewing another page with the embed.

**Comment by evansims** [comment]
I think we could handle this rather easily without a lot of extra leg work by checking if the page is contained within a frame and modifying links appropriately as necessary.

``` js
if ( window.self !== window.top ) { $('a').each(function() { $(this).attr('href') += '?embed'; }
```

Roughly that sort of deal.

**Comment by evansims** [comment]
Alright, I've implemented a new method of handling embed mode. We can remove ?embed from URLs now, if so desired. Though it might be nice for stat tracking.

At run time we now check if we're loaded inside a frame using JS. We can reference this state using the root.embeddedView flag, or if body has the #embed ID.

This is nice because we don't have to do any special server-side processing, or worrying about inserting params on URLs, or anything like that. Bonus: We can choose to bust out of framed views for doing things like signing up or managing your account, if necessary, by simply setting the $t->breakEmbed flag in the controller.
