### ISSUE TITLE
Feature - Global View Users

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#322]
When I look at the Global View Page, I want to know why I want to use this page and this tool.

Using the internet algo magic skills, surface:
Top liked posts
Top poster/users
Featured content curated by topic. 

Global User View:
https://crowdmap.com/posts?global=true

Related:
https://github.com/ushahidi/crowdmap-issues/issues/321

**Comment by brianherbert** [comment]
I think this will be a nonissue once there are filters in place so you can pick and choose what kind of posts are important to you. Issue for that: #324 

Agree? Or are you requesting something different?

**Comment by heatherleson** [comment]
I think it is that plus something different. 

I love websites that tell me what is most voted up and shared by whom and what topic. Twitter and Crackbook do this well. It builds engagement and user profiles. By curating that from a software level, it 'sells' its value /content

**Comment by evansims** [comment]
So, I don't think trying to shoehorn all this into the global stream view really makes sense. I really tend to think of that as more of a firehose-style view of content streaming in, rather than a discovery portal for learning about popular content.

However, I've always envisioned us implementing a curated 'Explore' section with hand-picked, featured maps and users. I think this is what we're really talking about here.
- We could offer a rotating view of the curated maps collection at the top of all the stream views in a carousel-like view.
- We could suggest users to follow when a user registers.
- I have some code stubbed in for a 'most popular posts' stream (but it isn't quite finished) that will be displayed in the header as an option alongside global and personal streams. That will just show the most upvoted posts in the last X hours, X being configurable.

**Comment by evansims** [comment]
Implemented a "featured users" and "featured maps" discovery portal in forthcoming UI update.
