### ISSUE TITLE
API Documentation and DELETE methods

### ISSUE THREAD

**Issue by dkobia** [ushahidi/crowdmap-issues#330]
Documentation needs to be very clear for each resource that the **DELETE** method is actually a **POST** with a **_METHOD=DELETE** parameter. I think you've noted this for Post deletion but nowhere else.

**Comment by brianherbert** [comment]
Actually, true DELETE and PUT works just fine (See #301) - In web applications, you have to include the extra method for any REST API.

Ultimately it depends on what browser you're using because most browsers don't support DELETE and PUT. http://stackoverflow.com/questions/165779/are-the-put-delete-head-etc-methods-available-in-most-web-browsers

All that said, I'll add a note to the docs to make this very clear as not everyone will understand.

**Comment by brianherbert** [comment]
Added notes about this on the docs under the https://api.crowdmap.com/developers/v1/#accessing-api section.

@dkobia I'm closing this now, but if you think this needs further explanation, please reopen.
