### ISSUE TITLE
Database or other tools

### ISSUE THREAD

**Issue by DBaranskiW** [ushahidi/crowdmap-issues#337]
We want to build long-term relationships.  Is there a way to capture names, email or other data for those participating on our map deployment?

**Comment by brianherbert** [comment]
At this time we aren't allowing mappers to access personal information of people who post to your map due to privacy concerns. This is possible with the Ushahidi Platform though since this information is available to administrators.

You can get usernames and the full name that the users entered but you will need to either do this manually or write a script to do it using the API. Documentation is here: https://api.crowdmap.com/developers/v1/
