### ISSUE TITLE
Embed Code Default Display

### ISSUE THREAD

**Issue by dkobia** [ushahidi/crowdmap-issues#341]
It'd be nice to have embed code that defaults to display in _Map Mode_ instead of detail mode.

Why? If for instance I have a blog post and want to embed the map, I'd rather the embed display the map than doubly displaying the blog post. Does this make sense? Right now I have the blog post above, then crowdmap display the same blog post in the embed with a comment section instead of the map which defeats the purpose... so maybe have an option to display either the map or detail?

Example attached.

![screenshot 2013-11-26 07 17 34](https://f.cloud.github.com/assets/184092/1621723/c89bb99e-5694-11e3-9aba-2f3ba145b37f.png)

**Comment by brianherbert** [comment]
This is something that has been on my personal wishlist. I've been hesitant to fiddle with the front end UI too much while the redesign is happening since I'm not sure how many changes will be lost with the new redesign. I'm going to leave this one up to @evansims, especially since I'm starting to prepare to wrap myself in the Ushahidi in the Cloud / VIP cocoon.

**Comment by evansims** [comment]
Yeah, I really want to give the whole embed system some love and attention. I probably won't get to this with this wave of the redesign push, but it's on my radar.

**Comment by brianherbert** [comment]
The embeds for posts are in, so I'm going to close this. I'll be opening another ticket for map embeds specifically.
