### ISSUE TITLE
Add Photos to API RSS Response

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#351]
Add images along with text in the RSS feeds.

Ping @moeden

**Comment by moeden** [comment]
I feel guilty for adding to your workload! Can I make a donation or support in any other way (given I'm not a coder)

**Comment by brianherbert** [comment]
No worries! Your feedback is payment enough!

**Comment by evansims** [comment]
I went ahead and implemented this today. If a post has a photo it will show up in the RSS feed as a [media:content element](http://www.rssboard.org/media-rss). Live example: https://api.crowdmap.com/v1/posts/?format=rss&has=photo

**Comment by moeden** [comment]
Thanks Evan - I've tried to generate a pdf newspaper which includes the images from https://api.crowdmap.com/v1/maps/windturbineswales/posts/?format=rss&has=photo
![clipboard01](https://f.cloud.github.com/assets/5020529/2147524/633d40c8-93d3-11e3-99a7-3eef96bde45f.jpg)
, and you can see that the newspaper doesn't scoop the images. Do you think this is a problem our end or with the RSS? The newspaper works fine with a 'standard' rss (such as this one http://ynnicymru.org.uk/blog/feed which produces this) 
![Uploading Clipboard02.jpg . . .]()

**Comment by evansims** [comment]
It appears the tool you're using doesn't support media enclosures and (I'm guessing) just pulls in HTML images from the description tag. Is this a tool you're developing, or something you're just putting to use? I can help point you in the right direction if you're building it, but otherwise you can work around this using an intermediary script of some kind.

Here's a quick Yahoo! Pipe I threw together that should output the content as you need it for your tool: http://pipes.yahoo.com/evansims/mediarss Paste the Crowdmap RSS URL in the input box there, hit "Run Pipe" and then right click the "Get as RSS" link. Use that URL as the source in your tool and it should work.

**Comment by moeden** [comment]
@evansims thanks for checking it out - it's a commercial offering which we use for other newsletters, but it's obviously struggling here. It's clear from the pipe that the issue is at the newsletter end rather than your api - I'll have a think about how we can use the RSS in another way to get the right outcome.

Thanks so much!

**Comment by moeden** [comment]
Hi @evansims, I saw that Yahoo Pipes was closing down, so I took another look at the 'feed with images' issue; I still can't get it to generate images with 'normal' feed readers although the text is fine. Tried with outlook and with Feedbucket. Any suggestions?

Thankyou in advance :)
