### ISSUE TITLE
Inbox takes over 30 seconds to load

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#54]
I have 60+ inbox items and it takes ages to load while the rest of the site is pretty snappy. I have a feeling we're probably making many queries on the API.

**Comment by evansims** [comment]
User lookups not getting cached, maybe? It shouldn't be taking that long for sure.

**Comment by brianherbert** [comment]
I'm seeing this when loading settings pages. Could be related.

![screen shot 2013-05-14 at 1 32 09 pm](https://f.cloud.github.com/assets/106068/499616/45814a5e-bc4f-11e2-9bd4-fd9a4e95173f.png)

**Comment by evansims** [comment]
Map settings is pulling in an obscene amount of information at once. We really need to refactor that and move more of it to the client side instead of processing it all at once on the server side. If you look at what I did with the user settings section last week, it dramatically improved page load performance. It was almost unusable before.

**Comment by evansims** [comment]
I believe my recent performance pass on caching should have resolved this issue. Closing for now.
