### ISSUE TITLE
Links on Chrome on iOS on site do nothing 

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#98]
I'm trying to click login and nothing happens, create new post, nothing happens. I manually type login URL in the browser and try to login but the form doesn't submit or do anything.

Seems like all of the click events for the modals are being caught by something other than their intended functions or if they are being caught by their intended functions, they simply aren't doing anything.

**Comment by evansims** [comment]
Hm, that's odd. Everything is working OK for me in Chrome on iOS. I got a Sentry notice a few minutes ago about modules not loading for someone; could that have been you?

_Update_ I just checked again on both iPad and iPhone and everything is working for me

**Comment by brianherbert** [comment]
If there was a tiny Firebug window on iOS, that would be awesome.

I'm trying to login on Chrome on iOS now and nothing is happening. I checked the URL and there's no hash at the end of the URL so I know it's being picked up somewhere. I actually have no idea how to diagnose this further without some kind of dev console.

**Comment by evansims** [comment]
[Remote Debugging](https://developers.google.com/chrome-developer-tools/docs/remote-debugging) is amazing for situations like this, but alas, it's only on Android.

Does this happen in Safari? You can use Safari's [version of remote debugging](http://moduscreate.com/enable-remote-web-inspector-in-ios-6/) to track down the cause if so. Since Chrome is really just a wrapper for Mobile Safari's UIWebView and they share their browser cache I'd have to think you'd be seeing it both places. Also, not to be "that guy," but have you tried clearing your cache?

Continuing to see if I can reproduce this.

**Comment by brianherbert** [comment]
I'm able to click around Safari just fine.

**Comment by brianherbert** [comment]
Just looping back to confirm this is still an issue.

Do all the links work fine in Chrome on Android?

**Comment by evansims** [comment]
Working in Android. I still can't reproduce it on my iOS devices. :(

**Comment by brianherbert** [comment]
I cleared my cache and it works now.

FML

![tumblr_inline_mh3eyq27xr1qa0z6j](http://cl.ly/image/2E1r0D3C2H1d/tumblr_inline_mh3eyq27XR1qa0z6j.gif)
