### ISSUE TITLE
Clustering needs to be tweaked

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#99]
Everything looks so crowded on mobile. Perhaps we need to parameterize the distance to cluster variables.

http://cl.ly/image/2A1y0i0q3o1y

**Comment by heatherleson** [comment]
Clustering is also confusing when you want to look at reports from the map view.

Actions: 
Map view from  https://crowdmap.com/posts/photos
Click on reports that are clustered: http://dl.dropbox.com/u/34693557/Screenshots/bk.png
There are no 'in between' screens to let you choose which reports from a map region you'd like to see. 
Clicked on New Zealand http://dl.dropbox.com/u/34693557/Screenshots/bl.png and received all the map reports.

clicked on South America in the region of Argentina and got this one post instead of list of 'clustered reports:" - http://dl.dropbox.com/u/34693557/Screenshots/bm.png

**Comment by brianherbert** [comment]
If you click on a cluster, you will be able to browse a list of those reports inside that clister. If you click and individual marker, you will see that individual post.

What types of actions would you like to perform in intermediary steps?

**Comment by heatherleson** [comment]
This depends on the zoom level. It is hit or miss at the moment.

If I am at the full zoom setting (eg. look at map view for all the latest posts) and click on an area, I get either a list or an individual marker. It might not be a huge navigation issue, but it is confusing at first.

**Comment by brianherbert** [comment]
Clusters now zoom in and break apart when you click on them. I think this will be much more pleasing and intuitive than it has been.

Closing.
